### ISSUE TITLE
main does not build: model_presentation.rs calls a cfg(test) method left by #1708

### ISSUE THREAD

**Issue by Virgile-pct** [Mesh-LLM/mesh-llm#1884]
`main` at 85b142df0 does not build `mesh-llm-host-runtime` outside of `cfg(test)`:

```
error[E0599]: no method named `upsert_served_model_descriptor` found for reference `&mesh::node::Node` in the current scope
  --> crates\mesh-llm-host-runtime\src\runtime\model_presentation.rs:44:18
   |
44 |             node.upsert_served_model_descriptor(descriptor).await;
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: there is a method `set_served_model_descriptors` with a similar name
```

Two pull requests merged six minutes apart, each green on its own base:

- 912e3071d, #1879 at 20:51Z, adds `runtime/model_presentation.rs`, whose `apply` calls `node.upsert_served_model_descriptor(...)` from production code.
- 218e402e7, #1708 at 20:56Z, reworks `mesh/node.rs` and leaves `upsert_served_model_descriptor` under `#[cfg(test)]` at `node.rs:1355`, since its own callers were tests and `runtime/local.rs`.

Neither branch saw the other, so the compile error only exists on `main`. The `Main · Quality` run on 85b142df0 fails in all three Clippy batches, and I hit it locally on Windows 11 by rebasing an unrelated test-only branch onto that head.

Smallest fix I can see: drop the `#[cfg(test)]` on `upsert_served_model_descriptor`, since it now has a production caller. I have a branch with exactly that change and a passing lib build, happy to open it or leave it to whoever owns the collision.
